### ISSUE TITLE
X-Real-IP and X-Real-Port headers

### ISSUE THREAD

**Issue by silverwind** [watson/original-url#1]
These are seldom used alternative headers that alias to `X-Forwarded-For` and `X-Forwarded-Port`. Notably, nginx has [support](http://nginx.org/en/docs/http/ngx_http_realip_module.html#real_ip_header) for the former. I think it might be valuable for this module the support them as a low-priority source for the original IP and port.

**Comment by trygve-lie** [comment]
Amazon ELB adds `X-Forwarded-For`: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html

Cisco A10 does the same.

**Comment by watson** [comment]
Thanks 👍 

It's added and released in v1.2.0 now

**Comment by silverwind** [comment]
Thanks!

I only see `X-Real-Port` in  https://github.com/watson/original-url/commit/47ed89b638bd6c50527afd8530de78a39f63ed1b, did you possibly forget about `X-Real-IP`?

**Comment by watson** [comment]
What information is in the `X-Real-IP` header that's needed for the returned result?

**Comment by silverwind** [comment]
You're right, I was somehow thinking about `X-Forwarded-For`, but you're not actually processing as it's not part of the original URL.

Actually, now that I think about it, both `X-Forwarded-Port` and `X-Real-Port` actually refer to the **source** port, not the **destination** port. I think they should actually not be processed because the source port is definitely not in the original URL.

**Comment by watson** [comment]
As far as I understand it, it's the source port of the proxy, i.e. the destination port that the client uses? But the only semi authority docs I've found on the subject is this: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-port

**Comment by silverwind** [comment]
Looks like you're right again. I found [this example](https://plone.lucidsolutions.co.nz/web/reverseproxyandcache/setting-nginx-http-x-forward-headers-for-reverse-proxy), which sets `X-Forwarded-Port` port to the destination port (443). `X-Real-Port` is missing in that example, but other examples I found set it to `$remote_port`, which in fact is the source port in nginx.

So, `X-Forwarded-Port` (dest port) and `X-Real-Port` (source port) refer to different ports and because the source port is not part of the original URL, `X-Real-Port` has to be removed from this module again. It still has other uses like identifying a user behind NAT.

Sorry for not properly researching this beforehand.

**Comment by watson** [comment]
Yeah, it looks like you're right. It seems that `X-Real-Port` is [usually](https://github.com/silverwind/droppy/wiki/Nginx-reverse-proxy) set to `$remote_port` in nginx config files. And `$remote_port` is according to [the documentation](http://nginx.org/en/docs/http/ngx_http_core_module.html) the "client port", just as `$remote_addr` is the "client ip". So it's the port that the client is connecting from, not to. I'll remove it again. Thanks a lot for the help resolving this 😄

**Comment by watson** [comment]
Solved in v1.2.1
